default_job = "run"

[jobs.check]
command = ["cargo", "check"]
need_stdout = false

[jobs.clippy]
command = ["cargo", "clippy", "--all-targets"]
need_stdout = false

[jobs.test]
command = ["cargo", "test"]
need_stdout = true

[jobs.run]
allow_warnings = true
background = false
command = ["cargo", "run"]
kill = ["kill", "-SIGTERM"]
need_stdout = true
on_change_strategy = "kill_then_restart"
watch = ["../../.env"]

[keybindings]
ctrl-d = "scroll-page(1)"
ctrl-u = "scroll-page(-1)"
esc = "back"
g = "scroll-to-top"
j = "scroll-lines(1)"
k = "scroll-lines(-1)"
shift-g = "scroll-to-bottom"
