[package]
name = "evops-ml"
edition = "2024"

[dependencies]
prost = "0.13.5"
tonic = "0.13.1"
tonic-reflection = "0.13.1"
tokio = { version = "1.45.1", features = ["rt-multi-thread", "macros"] }
eyre = "0.6.12"

[build-dependencies]
eyre = "0.6.12"
tonic-build = "0.13.1"